"""empty message

Revision ID: 3ed693771941
Revises: 
Create Date: 2018-07-09 23:04:09.381340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed693771941'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dns_cache',
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('ips', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('domain', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dns_cache')
    # ### end Alembic commands ###
